name: fireblend_web
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Eduardo <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  firebase: 5.0.4
  fireblend:
    git:
      url: https://github.com/darter/fireblend
      path: fireblend/

dev_dependencies:
  test: ^1.0.0
